import { useState } from 'react';
import './PlaylistDisplay.css';

function PlaylistDisplay({ analysis, tracks, imagePreview, spotifyUser, onSpotifyLogin, onAddMoreTracks, additionCount, addingMore, playlistTitle, onTitleChange, onRemoveTrack }) {
  const [currentlyPlaying, setCurrentlyPlaying] = useState(null);
  const [saving, setSaving] = useState(false);
  const [savedPlaylist, setSavedPlaylist] = useState(null);
  const [saveError, setSaveError] = useState(null);
  const [isEditingTitle, setIsEditingTitle] = useState(false);

  const togglePlay = (track) => {
    if (currentlyPlaying === track.id) {
      setCurrentlyPlaying(null);
    } else {
      setCurrentlyPlaying(track.id);
    }
  };

  const openInSpotify = (track) => {
    window.open(track.spotifyUrl, '_blank');
  };

  const saveToSpotify = async () => {
    setSaving(true);
    setSaveError(null);

    try {
      const trackUris = tracks.map(t => t.uri).filter(Boolean);

      const response = await fetch('/api/create-playlist', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        credentials: 'include', // Send cookies automatically
        body: JSON.stringify({
          name: playlistTitle || `RelicRadio - ${analysis?.mood || 'Vibes'}`,
          description: `Generated by RelicRadio based on image analysis. Mood: ${analysis?.mood || 'Unknown'}`,
          trackUris
        })
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to save playlist');
      }

      setSavedPlaylist(data);
    } catch (err) {
      setSaveError(err.message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="playlist-display">
      <div className="playlist-header">
        {imagePreview && (
          <div className="header-image">
            <img src={imagePreview} alt="Uploaded" />
          </div>
        )}
        <div className="header-content">
          <span className="playlist-label">Generated Playlist</span>
          <div className="playlist-title-container">
            {isEditingTitle ? (
              <input
                type="text"
                className="playlist-title-input"
                value={playlistTitle}
                onChange={(e) => onTitleChange(e.target.value)}
                onBlur={() => setIsEditingTitle(false)}
                onKeyDown={(e) => e.key === 'Enter' && setIsEditingTitle(false)}
                autoFocus
              />
            ) : (
              <h2 onClick={() => setIsEditingTitle(true)} className="playlist-title-editable">
                {playlistTitle || 'My Moodlist'}
                <svg className="edit-icon" viewBox="0 0 24 24" width="16" height="16" fill="currentColor">
                  <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"/>
                </svg>
              </h2>
            )}
          </div>
          {analysis && (
            <div className="analysis-info">
              <p className="mood">Mood: {analysis.mood}</p>
              <div className="themes">
                {analysis.themes?.map((theme, i) => (
                  <span key={i} className="theme-tag">{theme}</span>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      <div className="tracks-list">
        {tracks.map((track, index) => (
          <div key={track.id} className={`track-item ${currentlyPlaying === track.id ? 'expanded' : ''}`}>
            <div className="track-row">
              <span className="track-number">{index + 1}</span>
              <img
                src={track.albumArt}
                alt={track.album}
                className="track-album-art"
              />
              <div className="track-info">
                <p className="track-name">{track.name}</p>
                <p className="track-artist">{track.artist}</p>
              </div>
              <div className="track-actions">
                <button
                  className={`play-button ${currentlyPlaying === track.id ? 'playing' : ''}`}
                  onClick={() => togglePlay(track)}
                  title="Play in Spotify"
                >
                  {currentlyPlaying === track.id ? '✕' : '▶'}
                </button>
                <button
                  className="spotify-button"
                  onClick={() => openInSpotify(track)}
                  title="Open in Spotify"
                >
                  <svg viewBox="0 0 24 24" width="20" height="20">
                    <path fill="currentColor" d="M12 0C5.4 0 0 5.4 0 12s5.4 12 12 12 12-5.4 12-12S18.66 0 12 0zm5.521 17.34c-.24.359-.66.48-1.021.24-2.82-1.74-6.36-2.101-10.561-1.141-.418.122-.779-.179-.899-.539-.12-.421.18-.78.54-.9 4.56-1.021 8.52-.6 11.64 1.32.42.18.479.659.301 1.02zm1.44-3.3c-.301.42-.841.6-1.262.3-3.239-1.98-8.159-2.58-11.939-1.38-.479.12-1.02-.12-1.14-.6-.12-.48.12-1.021.6-1.141C9.6 9.9 15 10.561 18.72 12.84c.361.181.54.78.241 1.2zm.12-3.36C15.24 8.4 8.82 8.16 5.16 9.301c-.6.179-1.2-.181-1.38-.721-.18-.601.18-1.2.72-1.381 4.26-1.26 11.28-1.02 15.721 1.621.539.3.719 1.02.419 1.56-.299.421-1.02.599-1.559.3z"/>
                  </svg>
                </button>
                <button
                  className="remove-button"
                  onClick={() => onRemoveTrack(track.id)}
                  title="Remove from playlist"
                >
                  <svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor">
                    <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
                  </svg>
                </button>
              </div>
            </div>
            {currentlyPlaying === track.id && (
              <div className="spotify-embed">
                <iframe
                  src={`https://open.spotify.com/embed/track/${track.id}?utm_source=generator&theme=0`}
                  width="100%"
                  height="152"
                  frameBorder="0"
                  allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
                  loading="lazy"
                  title={`Play ${track.name}`}
                />
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="playlist-footer">
        <p>{tracks.length} songs</p>

        <div className="add-more-section">
          {additionCount < 3 ? (
            <button
              className="add-more-button"
              onClick={onAddMoreTracks}
              disabled={addingMore}
            >
              {addingMore ? 'Adding songs...' : '+ Add More Songs'}
            </button>
          ) : (
            <span className="track-limit-message">Track Limit Reached</span>
          )}
        </div>

        <div className="save-section">
          {savedPlaylist ? (
            <a
              href={savedPlaylist.playlistUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="saved-link"
            >
              Saved! Open in Spotify
            </a>
          ) : spotifyUser ? (
            <button
              className="save-button"
              onClick={saveToSpotify}
              disabled={saving}
            >
              {saving ? 'Saving...' : 'Save to Spotify'}
            </button>
          ) : (
            <button
              className="connect-button"
              onClick={onSpotifyLogin}
            >
              Connect Spotify to Save
            </button>
          )}
          {saveError && <p className="save-error">{saveError}</p>}
        </div>
      </div>
    </div>
  );
}

export default PlaylistDisplay;
